import { ScrollTrigger } from "gsap/ScrollTrigger";
import React, { useRef, useEffect } from "react";
import Head from "next/head";
import { gsap } from "gsap";

export default function Home() {
  gsap.registerPlugin(ScrollTrigger);

  const container = useRef(null);

  useEffect(() => {
    const element = container.current;
    let sections = gsap.utils.toArray(".project");
    gsap.to(sections, {
      xPercent: -100 * (sections.length - 1),
      ease: "none",
      scrollTrigger: {
        trigger: element,
        pin: true,
        scrub: true,
        snap: 1 / (sections.length - 1),
        end: "+=3000",
      },
    });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="homePage">
        <p className="homeText">home</p>
      </div>
      <div className="container" ref={container}>
        <div className="project" style={{ background: "red" }}>
          <p>Project</p>
        </div>
        <div className="project" style={{ background: "gold" }}>
          <p>Project</p>
        </div>
        <div className="project" style={{ background: "blue" }}>
          <p>Project</p>
        </div>
        <div className="project" style={{ background: "green" }}>
          <p>Project</p>
        </div>
        <div className="project" style={{ background: "blueviolet" }}>
          <p>Project</p>
        </div>
      </div>
      <div className="contactPage">
        <p className="contactText">contact</p>
      </div>
    </>
  );
}
